#index:
#    path: /
#    controller: App\Controller\AnnoncesController::index
# config/routes.yaml
app_images:
    path: /images/{id}
    controller: App\Controller\ImageController::show
    requirements:
        id: \d+
